Models/Contato.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ControleContatos.Models
{
    [Table("CONTATO")]
    public class Contato
    {
        
        [Key]
        [Display(Name ="Código")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o nome do contato.")]
        [Display(Name ="Nome")]
        [Column("Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Digite o email do contato.")]
        [EmailAddress(ErrorMessage = "O e-mail informado nao é válido.")]
        [Display(Name ="email")]
        [Column("Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Digite o celular do contato.")]
        [Phone(ErrorMessage = "o Celular informado não é válido.")]
        [Display(Name ="Celular")]
        [Column("Celular")]
        public string Celular { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace ControleContatos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Usuario.cs
using ControleContatos.Enums;
using System;

namespace ControleContatos.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
        
        public PerfilEnum Perfil{get; set;}
        public string Senha { get; set; }
        public DateTime DataCadastro { get; set; }
        public DateTime? DataAtualizacao { get; set; }
    }
}

Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ControleContatos.Models;
using ControleContatos.Repositorio;

namespace ControleContatos.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;
        public ContatoController(IContatoRepositorio contatoRepositorio)
        {
            _contatoRepositorio = contatoRepositorio;
        }
        public IActionResult Index()
        {
            List<Contato> contatos = _contatoRepositorio.BuscarTodos();
            
            return View(contatos);
        }
        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            Contato contato = _contatoRepositorio.ListarPorId(id);

            return View(contato);
        }
        public IActionResult ApagarConfirmacao(int id)
        {
            Contato contato = _contatoRepositorio.ListarPorId(id);

            return View(contato);
        }
        public IActionResult Apagar(int id)
        {
            try
            {
               bool apagado = _contatoRepositorio.Apagar(id);
               if(apagado)
               {
                   TempData["MensagemSucesso"] = "Contato apagado com sucesso!";                

               }
               else
               {
                    TempData["MensagemErro"]="Ops, não conseguimos apagar seu contato";
               }
                 return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                
                TempData["MensagemErro"]=$"Ops, não conseguimos apagar seu contato, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }
        [HttpPost]
        public IActionResult Criar(Contato contato)
        {
            try
            {
                if(ModelState.IsValid)
            {
                 _contatoRepositorio.Adicionar(contato);
                 TempData["MensagemSucesso"] = "Contato cadastrado com sucesso!";
                 return RedirectToAction("Index");
            }
            return View(contato);
            }
            catch (System.Exception erro)
            {
                
                TempData["MensagemErro"]=$"Ops, não conseguimos cadastrar seu contato, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
           
        }

        [HttpPost]
        public IActionResult Alterar(Contato contato)
        {
           try
           {
                if(ModelState.IsValid)
            {
                  _contatoRepositorio.Atualizar(contato);
                   TempData["MensagemSucesso"] = "Contato alterado com sucesso!";
                  return RedirectToAction("Index");

            }
            return View("Editar",contato);

           }
           catch (System.Exception erro)
           {
               
               TempData["MensagemErro"]=$"Ops, não conseguimos atualizar seu contato, tente novamente, detalhe do erro: {erro.Message}";
               return RedirectToAction("Index");
           }
          
        }

               
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ControleContatos.Models;

namespace ControleContatos.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ControleContatos.Models;

namespace ControleContatos.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }       
    }
}

Views/Contato/ApagarConfirmacao.cshtml
@model Contato
@{
    ViewData["Title"] = "Confirmação apagar o contato";
}
<div class="text-left">
    <h3>Realmente deseja apagar o contato(@Model.Nome)?</h3>
</div>
<a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger" role="button" asp-controller="Contato" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>

Views/Contato/Criar.cshtml
@model Contato
@{
    ViewData["Title"] = "Criar Contato";
}

<div class="text-center">

  <h2 class="display-4">Cadastrar Contato</h2>

</div>

<form asp-controller="Contato" asp-action="Criar" method="post">
  
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Digite seu nome">
    @Html.ValidationMessageFor(x=>x.Nome)
  </div>
  <div class="form-group">
    <label for="email">E-mail</label>
    <input type="text" asp-for="Email" class="form-control" placeholder="Digite o seu email">
    @Html.ValidationMessageFor(x=>x.Email)
  </div>
  <div class="form-group">
    <label for="celular">Celular</label>
    <input type="text" asp-for="Celular" class="form-control" placeholder="Digite seu celular">
    @Html.ValidationMessageFor(x=>x.Celular)
  </div>
  
  <button type="submit" class="btn btn-primary">Adicionar</button>
  <a class="btn btn-primary" asp-controller="Contato" asp-action="Index" role="button" >Voltar</a>
</form>

Views/Contato/Editar.cshtml
@model Contato
@{
    ViewData["Title"] = "Editar Contato";
}

<div class="text-center">

  <h2 class="display-4">Editar Contato</h2>

</div>

<form asp-controller="Contato" asp-action="Alterar" method="post">

  <input type="hidden" asp-for="Id"/>

  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Digite seu nome">
    @Html.ValidationMessageFor(x=>x.Nome)
  </div>
  <div class="form-group">
    <label for="email">E-mail</label>
    <input type="text" asp-for="Email" class="form-control" placeholder="Digite o seu email">
    @Html.ValidationMessageFor(x=>x.Email)
  </div>
  <div class="form-group">
    <label for="celular">Celular</label>
    <input type="text" asp-for="Celular" class="form-control" placeholder="Digite seu celular">
    @Html.ValidationMessageFor(x=>x.Celular)
  </div>
  
  <button type="submit" class="btn btn-primary">Alterar</button>
  <a class="btn btn-primary" asp-controller="Contato" asp-action="Index" role="button" >Voltar</a>
</form>

Views/Contato/Index.cshtml
@model List<Contato>

@{
    ViewData["Title"] = "Listagem de Contatos";
}
<div class="d-grid gap-2 d-md-flex justify-contend-md-start">
  <a  class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar novo contato</a>
</div>
<br/>
<div class="text-center">

@if (TempData["MensagemSucesso"]!=null)
{
  <div class="alert alert-success" role="alert">
  <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
  @TempData["MensagemSucesso"]
</div>
}
@if (TempData["MensagemErro"]!=null)
{
    <div class="alert alert-danger" role="alert">
      <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
      @TempData["MensagemErro"]
    </div>
    <br/>
}
  <h1 class="display-4">Listagem de Contatos</h1>

<table class="table" id="table-contato">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">E-mail</th>
      <th scope="col">Celular</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
   @if(Model!= null && Model.Any())
   {
     foreach(Contato contato in Model)
     {
        <tr>
      <th scope="row">@contato.Id</th>
      <td>@contato.Nome</td>
      <td>@contato.Email</td>
      <td>@contato.Celular</td>
      <td>
          <div class="btn-group" role="group">
            <a role="button" class="btn btn-primary" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="Editar">Editar</a>
            <a role="button" class="btn btn-danger" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
            
          </div>
      </td>
    </tr>
     }
   }   
  </tbody>
</table>


</div>

   
 

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo</h1>
    <p>Sistema de Controle de Contatos</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.5/datatables.min.css"/>
 

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de Contatos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuário</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Controle de Contatos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.5/datatables.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Usuario/Index.cshtml
@model List<Usuario>

@{
    ViewData["Title"] = "Listagem de Usuarios";
}
<div class="d-grid gap-2 d-md-flex justify-contend-md-start">
  <a  class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar novo usuário</a>
</div>
<br/>
<div class="text-center">

@if (TempData["MensagemSucesso"]!=null)
{
  <div class="alert alert-success" role="alert">
  <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
  @TempData["MensagemSucesso"]
</div>
}
@if (TempData["MensagemErro"]!=null)
{
    <div class="alert alert-danger" role="alert">
      <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
      @TempData["MensagemErro"]
    </div>
    <br/>
}
  <h1 class="display-4">Listagem de Usuários</h1>

<table class="table" id="table-usuario">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Login</th>
      <th scope="col">Email</th>
      <th scope="col">Data de cadastro</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
   @if(Model!= null && Model.Any())
   {
     foreach(Usuario usuario in Model)
     {
        <tr>
      <th scope="row">@usuario.Id</th>
      <td>@usuario.Nome</td>
      <td>@usuario.Login</td>
      <td>@usuario.Email</td>
      <td>@usuario.DataCadastro</td>
      <td>
          <div class="btn-group" role="group">
            <a role="button" class="btn btn-primary" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="Editar">Editar</a>
            <a role="button" class="btn btn-danger" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="ApagarConfirmacao">Apagar</a>
            
          </div>
      </td>
    </tr>
     }
   }   
   else
   {
     <tr class="odd"><td valign="top" colspan="5">Nenhum usuario encontrado</td></tr>
   }
  </tbody>
</table>


</div>

   
 